// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkidBDHz_7A58Cy6fV3eT0O1ZbfTZ0rW0',
    appId: '1:70673637366:web:36fc42abc50e121ec631d7',
    messagingSenderId: '70673637366',
    projectId: 'flutter-pro-firebase-diary660',
    authDomain: 'flutter-pro-firebase-diary660.firebaseapp.com',
    storageBucket: 'flutter-pro-firebase-diary660.firebasestorage.app',
    measurementId: 'G-GTHV5ZJ426',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2HCjDJ0WpnPmCrt3QBFE4GjDgtsNo4w',
    appId: '1:70673637366:android:101150de301461dcc631d7',
    messagingSenderId: '70673637366',
    projectId: 'flutter-pro-firebase-diary660',
    storageBucket: 'flutter-pro-firebase-diary660.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkidBDHz_7A58Cy6fV3eT0O1ZbfTZ0rW0',
    appId: '1:70673637366:web:42cff6af43d14605c631d7',
    messagingSenderId: '70673637366',
    projectId: 'flutter-pro-firebase-diary660',
    authDomain: 'flutter-pro-firebase-diary660.firebaseapp.com',
    storageBucket: 'flutter-pro-firebase-diary660.firebasestorage.app',
    measurementId: 'G-RZFGQ069BW',
  );

}